WITH
NEW_DATA AS(
SELECT
BOOK_ID,
SUM(SALES) SALES
FROM BOOK_SALES
WHERE EXTRACT(YEAR FROM SALES_DATE) = 2022 AND EXTRACT(MONTH FROM SALES_DATE) = 1
GROUP BY BOOK_ID
),
NEW_DATA2 AS(
SELECT
B.BOOK_ID,
B.CATEGORY,
B.AUTHOR_ID,
B.PRICE,
N.SALES
FROM BOOK B
INNER JOIN NEW_DATA N
ON B.BOOK_ID = N.BOOK_ID
)

SELECT
A.author_id,
A.author_name,
A.CATEGORY,
SUM(A.TOTAL_SALES) TOTAL_SALES
FROM(
SELECT
N.AUTHOR_ID,
A.AUTHOR_NAME,
N.CATEGORY,
(PRICE * SALES) TOTAL_SALES
FROM NEW_DATA2 N
INNER JOIN AUTHOR A
ON N.AUTHOR_ID = A.AUTHOR_ID
) A
GROUP BY A.author_id, A.author_name, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC