SELECT
 A.PRODUCT_CODE,
 A.PRICE * SUM(A.SALES_AMOUNT) AS SALES
FROM (
SELECT
    P.PRODUCT_CODE,
    O.PRODUCT_ID,
    P.PRICE,
    O.SALES_AMOUNT
FROM OFFLINE_SALE AS O
LEFT JOIN PRODUCT AS P
ON O.PRODUCT_ID = P.PRODUCT_ID)A
GROUP BY PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC 