--코드를 입력하세요
SELECT
A.*
FROM(
SELECT
TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE,
PRODUCT_ID,
USER_ID,
SALES_AMOUNT
FROM ONLINE_SALE ONS

UNION

SELECT
TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE,
PRODUCT_ID,
NULL USER_ID,
SALES_AMOUNT
FROM OFFLINE_SALE
) A
WHERE EXTRACT(YEAR FROM TO_DATE(SALES_DATE,'YYYY-MM-DD')) = 2022 AND EXTRACT(MONTH FROM TO_DATE(SALES_DATE,'YYYY-MM-DD')) = 3