-- 코드를 입력하세요
SELECT
A.ANIMAL_ID,
A.NAME
FROM (SELECT
OUTS.ANIMAL_ID,
OUTS.NAME,
OUTS.DATETIME - INS.DATETIME AS DATA
FROM ANIMAL_OUTS OUTS
INNER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
ORDER BY DATA DESC
     )A
WHERE ROWNUM<=2