-- 코드를 입력하세요
SELECT
A.WRITER_ID,
U.NICKNAME,
U.CITY||' '|| U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 "전체주소",
CONCAT(CONCAT(CONCAT(CONCAT(SUBSTR(TLNO,1,3),'-'),SUBSTR(TLNO,4,4)),'-'),SUBSTR(TLNO,8,8)) 전화번호

FROM (
SELECT
B.WRITER_ID,
COUNT(B.WRITER_ID) COUNT
FROM USED_GOODS_BOARD B
GROUP BY B.WRITER_ID
) A
INNER JOIN USED_GOODS_USER U
ON A.WRITER_ID = U.USER_ID
WHERE A.COUNT>=3
ORDER BY A.WRITER_ID DESC