-- 코드를 입력하세요
WITH REVIEW AS(
SELECT
REST_ID,
ROUND(AVG(REVIEW_SCORE),2) SCORE
FROM REST_REVIEW
GROUP BY REST_ID
)

SELECT
R.REST_ID,
R.REST_NAME,
R.FOOD_TYPE,
R.FAVORITES,
R.ADDRESS,
REVIEW.SCORE
FROM REST_INFO R
INNER JOIN REVIEW REVIEW
ON R.REST_ID = REVIEW.REST_ID
WHERE R.ADDRESS LIKE '서울%'
ORDER BY REVIEW.SCORE DESC, R.FAVORITES DESC