-- 코드를 작성해주
SELECT
ROUTE,
CONCAT(CAST(ROUND(SUM(D_BETWEEN_DIST),1) AS CHAR),"km") TOTAL_DISTANCE,
CONCAT(ROUND(AVG(D_BETWEEN_DIST),2), "km") AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUTE DESC