-- 코드를 입력하세요
SELECT
O.PRODUCT_ID,
R.PRODUCT_NAME,
SUM(R.PRICE * O.AMOUNT) TOTAL_SALES
FROM FOOD_ORDER O
INNER JOIN FOOD_PRODUCT R
ON O.PRODUCT_ID = R.PRODUCT_ID
WHERE TO_CHAR(O.PRODUCE_DATE,'YYYY-MM-DD') BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY R.PRODUCT_NAME,O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC