-- 코드를 입력하세요
SELECT
A.FLAVOR
FROM(
SELECT
F.FLAVOR,
F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) PRICE
FROM FIRST_HALF F
INNER JOIN JULY J
ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR, F.TOTAL_ORDER
ORDER BY PRICE DESC
)A
WHERE ROWNUM<=3