-- 코드를 입력하세요
WITH
MAX_MEMBER_REVIEW AS(
SELECT
A.*
FROM(
SELECT
MEMBER_ID,
COUNT(MEMBER_ID) NUM      
FROM REST_REVIEW 
GROUP BY MEMBER_ID
ORDER BY NUM DESC
)A
WHERE ROWNUM = 1
),
REST_REVIEW2 AS(
SELECT
R.MEMBER_ID,
P.REVIEW_TEXT,
TO_CHAR(P.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM MAX_MEMBER_REVIEW R
INNER JOIN REST_REVIEW P
ON R.MEMBER_ID = P.MEMBER_ID
)

SELECT
P.MEMBER_NAME,
R2.REVIEW_TEXT,
R2.REVIEW_DATE
FROM REST_REVIEW2 R2
INNER JOIN MEMBER_PROFILE P
ON R2.MEMBER_ID = P.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT


