-- 코드를 입력하세요
SELECT
B.CATEGORY,
SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
LEFT JOIN BOOK B
ON BS.BOOK_ID = B.BOOK_ID
WHERE EXTRACT(YEAR FROM BS.SALES_DATE) = 2022 AND EXTRACT(MONTH FROM BS.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY 1