-- 코드를 입력하세요
WITH EXTRACT_NAME AS (
    SELECT
    PRODUCT_NAME,
    CATEGORY,
    PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
)

SELECT
A.*,
E.PRODUCT_NAME
FROM (
SELECT
CATEGORY,
MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
GROUP BY CATEGORY
HAVING CATEGORY IN ('과자','국','김치','식용유')
)A
INNER JOIN EXTRACT_NAME E
ON A.CATEGORY = E.CATEGORY AND MAX_PRICE = E.PRICE
ORDER BY MAX_PRICE DESC
-- SELECT * FROM EXTRACT_NAME